import os
import re
from typing import Any, Dict, List, Optional, Tuple

import psycopg2
from psycopg2.extras import RealDictCursor
from dotenv import load_dotenv

from app.models import (
    CareerProfileRequest,
    SalaryInsight,
    RoleIntelligenceResult,
    TargetSalaryInsight,
)

load_dotenv()


class SalaryService:
    """
    Phase 2B Salary Engine v2.

    This is still an estimate engine, not a guaranteed salary predictor.

    It uses:
    - primary cluster / canonical role
    - experience band
    - city multiplier
    - role intelligence confidence
    - skill readiness
    """

    def __init__(self):
        self.database_url = os.getenv("DATABASE_URL")

    def calculate_salary(
        self,
        profile: CareerProfileRequest,
        role_cluster: str,
        role_intelligence: Optional[RoleIntelligenceResult] = None
    ) -> SalaryInsight:

        salary_band = self._load_salary_band(role_cluster, role_intelligence)

        if not salary_band:
            return self._fallback_salary(profile, role_cluster)

        base_min, base_max, experience_label = self._select_experience_band(
            profile.experience_years,
            salary_band
        )

        city_multiplier = self._city_multiplier(profile.city)

        skill_multiplier = self._skill_readiness_multiplier(role_intelligence)

        market_min = base_min * city_multiplier
        market_max = base_max * city_multiplier * skill_multiplier

        market_min = round(market_min, 1)
        market_max = round(market_max, 1)

        if market_max < market_min:
            market_max = market_min + 1

        salary_gap = self._calculate_salary_gap(
            profile.current_salary_lpa,
            market_min,
            market_max
        )

        confidence = self._build_confidence_note(
            salary_band=salary_band,
            role_intelligence=role_intelligence,
            experience_label=experience_label,
            city=profile.city,
            skill_multiplier=skill_multiplier
        )

        return SalaryInsight(
            current_salary_lpa=profile.current_salary_lpa,
            market_min_lpa=market_min,
            market_max_lpa=market_max,
            salary_gap_lpa=salary_gap,
            confidence=confidence
        )

    def calculate_target_salary_insights(
        self,
        profile: CareerProfileRequest,
        growth_paths: List[Dict[str, Any]],
        target_roles: List[str],
    ) -> List[TargetSalaryInsight]:
        """
        Calculates salary potential for recommended target roles.

        This is separate from current-role salary calculation.
        Current salary uses the user's current role cluster.
        Target salary uses recommended roles generated by AI.

        It reads salary_bands_v2 using mapped target clusters like:
        - Cloud Support Engineer -> Cloud Support
        - DevOps Engineer -> DevOps
        - Production Support Engineer -> Production Support
        """

        target_candidates = self._collect_target_role_candidates(
            growth_paths=growth_paths,
            target_roles=target_roles,
        )

        if not target_candidates:
            return []

        target_candidates = self._prioritize_target_candidates(target_candidates)
        insights: List[TargetSalaryInsight] = []
        seen_roles = set()

        for candidate in target_candidates:
            target_role = candidate["target_role"]
            fit_level = candidate["fit_level"]
            path_name = candidate["path_name"]

            normalized_role = self._normalize_text(target_role)

            if normalized_role in seen_roles:
                continue

            seen_roles.add(normalized_role)

            target_cluster = self._map_target_role_to_salary_cluster(
                target_role=target_role,
                path_name=path_name,
            )

            salary_band = self._load_salary_band_by_cluster(target_cluster)

            if not salary_band:
                continue

            estimated_min, estimated_max, experience_label = (
                self._calculate_target_salary_range(
                    profile=profile,
                    salary_band=salary_band,
                    fit_level=fit_level,
                )
            )

            salary_upside_note = self._build_target_salary_note(
                target_role=target_role,
                target_cluster=target_cluster,
                fit_level=fit_level,
                experience_label=experience_label,
            )

            insights.append(
                TargetSalaryInsight(
                    target_role=target_role,
                    estimated_min_lpa=estimated_min,
                    estimated_max_lpa=estimated_max,
                    fit_level=fit_level,
                    salary_upside_note=salary_upside_note,
                )
            )

            if len(insights) >= 3:
                break

        return insights
    
    def _collect_target_role_candidates(
        self,
        growth_paths: List[Dict[str, Any]],
        target_roles: List[str],
    ) -> List[Dict[str, str]]:
        """
        Collects target roles from both:
        1. growth_paths target_roles
        2. top-level target_roles

        This is important because sometimes growth_paths are detailed,
        and sometimes top-level target_roles are cleaner.
        """

        candidates: List[Dict[str, str]] = []

        if isinstance(growth_paths, list):
            for path in growth_paths:
                if not isinstance(path, dict):
                    continue

                fit_level = str(path.get("fit_score", "Medium"))
                path_name = str(path.get("path_name", "Recommended Path"))
                roles = path.get("target_roles", [])

                if not isinstance(roles, list):
                    continue

                for role in roles:
                    role_text = str(role).strip()

                    if role_text:
                        candidates.append(
                            {
                                "target_role": role_text,
                                "fit_level": fit_level,
                                "path_name": path_name,
                            }
                        )

        if isinstance(target_roles, list):
            for role in target_roles:
                role_text = str(role).strip()

                if role_text:
                    candidates.append(
                        {
                            "target_role": role_text,
                            "fit_level": "Medium",
                            "path_name": "Recommended Target Role",
                        }
                    )

        return candidates

    def _prioritize_target_candidates(
        self,
        candidates: List[Dict[str, str]]
    ) -> List[Dict[str, str]]:
        """
        Cleans and prioritizes target roles before salary calculation.

        Why:
        AI can generate many similar roles inside growth paths.
        Example:
        - Cloud Support Engineer
        - Cloud Operations Engineer
        - Technical Support Engineer

        For salary insight card, we want cleaner and more meaningful options.
        """

        if not candidates:
            return []

        generic_role_keywords = [
            "technical support engineer",
            "support engineer",
            "associate",
            "specialist"
        ]

        preferred_keywords_order = [
            "cloud support engineer",
            "devops engineer",
            "production support engineer",
            "senior api tester",
            "automation qa engineer",
            "sdet",
            "senior react developer",
            "frontend engineer",
            "backend engineer",
            "data analyst",
            "business analyst",
            "product analyst",
            "scrum master",
            "cloud engineer",
            "security tester",
            "power bi developer"
        ]

        def score_candidate(candidate: Dict[str, str]) -> int:
            role = self._normalize_text(candidate.get("target_role", ""))
            fit = self._normalize_text(candidate.get("fit_level", "Medium"))
            path_name = self._normalize_text(candidate.get("path_name", ""))

            score = 0

            # Prefer top-level target roles because they are usually cleaner.
            if path_name == "recommended target role":
                score += 30

            # Prefer high fit.
            if "high" in fit:
                score += 25
            elif "medium" in fit:
                score += 15
            elif "low" in fit:
                score += 5

            # Prefer specific business-relevant target roles.
            for index, keyword in enumerate(preferred_keywords_order):
                if keyword in role:
                    score += 50 - index
                    break

            # Penalize generic roles if better roles are available.
            for keyword in generic_role_keywords:
                if keyword == role or keyword in role:
                    score -= 20

            return score

        sorted_candidates = sorted(
            candidates,
            key=score_candidate,
            reverse=True
        )

        cleaned: List[Dict[str, str]] = []
        seen_normalized_roles = set()

        for candidate in sorted_candidates:
            role = candidate.get("target_role", "").strip()
            normalized_role = self._normalize_text(role)

            if not normalized_role:
                continue

            if normalized_role in seen_normalized_roles:
                continue

            seen_normalized_roles.add(normalized_role)
            cleaned.append(candidate)

        return cleaned
    
    def _calculate_target_salary_range(
        self,
        profile: CareerProfileRequest,
        salary_band: Dict[str, Any],
        fit_level: str,
    ) -> Tuple[float, float, str]:
        """
        Calculates target role salary range using:
        - user's current experience
        - city multiplier
        - fit-level adjustment

        High fit: normal band
        Medium fit: slightly reduced because user is still transitioning
        Low fit: more reduced because it is a stretch path
        """

        base_min, base_max, experience_label = self._select_experience_band(
            profile.experience_years,
            salary_band,
        )

        city_multiplier = self._city_multiplier(profile.city)
        fit_multiplier = self._target_fit_multiplier(fit_level)

        estimated_min = round(base_min * city_multiplier * fit_multiplier, 1)
        estimated_max = round(base_max * city_multiplier * fit_multiplier, 1)

        if estimated_max < estimated_min:
            estimated_max = estimated_min + 1

        return estimated_min, estimated_max, experience_label


    def _target_fit_multiplier(self, fit_level: str) -> float:
        normalized_fit = fit_level.lower()

        if "high" in normalized_fit:
            return 1.0

        if "low" in normalized_fit:
            return 0.82

        return 0.90
    
    def _map_target_role_to_salary_cluster(
        self,
        target_role: str,
        path_name: str,
    ) -> str:
        """
        Maps AI-generated target roles to salary_bands_v2 role_key.

        This is rule-based for now.
        Later Phase 2 can improve this using canonical role lookup or embeddings.
        """

        text = self._normalize_text(f"{target_role} {path_name}")

        mapping_rules = [
            # Support / Cloud / DevOps
            (["cloud support", "cloud operations", "cloud administrator", "technical support engineer"], "Cloud Support"),
            (["production support", "application support engineer ii", "incident manager"], "Production Support"),
            (["application support"], "Application Support"),
            (["junior devops", "devops associate", "devops engineer", "devops"], "DevOps"),
            (["site reliability engineer", "sre", "junior sre"], "DevOps"),
            (["cloud engineer", "cloud infrastructure"], "Cloud Engineering"),

            # QA / Testing
            (["manual qa", "manual tester", "qa tester", "software tester"], "Testing/QA"),
            (["automation qa", "automation tester", "selenium"], "Automation Testing"),
            (["api tester", "api testing", "senior api tester"], "API Testing"),
            (["performance tester", "load tester", "jmeter"], "Performance Testing"),
            (["sdet"], "SDET"),

            # Software development
            (["react", "frontend", "ui developer", "angular"], "Frontend Engineering"),
            (["full stack", "fullstack"], "Full Stack Engineering"),
            (["backend", "java developer", "spring", "node", "python backend", ".net", "api developer"], "Backend Engineering"),

            # Data / AI
            (["data analyst", "reporting analyst"], "Data Analytics"),
            (["power bi", "bi analyst", "business intelligence"], "Business Intelligence"),
            (["data engineer", "etl"], "Data Engineering"),
            (["data scientist"], "Data Science"),
            (["ml engineer", "machine learning engineer", "ai engineer"], "AI/ML"),
            (["ai automation", "llm app", "genai"], "AI Automation"),
            (["mlops"], "MLOps"),

            # BA / Product / Agile
            (["business analyst", "it ba", "functional analyst"], "Business Analysis"),
            (["product analyst", "growth analyst"], "Product Analysis"),
            (["scrum master", "agile coach"], "Agile Delivery"),
            (["project manager", "program manager"], "Agile Delivery"),
            (["project coordinator", "pmo"], "Project Coordination"),

            # Infra / Security / Others
            (["database", "sql developer", "plsql", "dba"], "Database Engineering"),
            (["security tester", "penetration", "vapt"], "Security Testing"),
            (["security analyst", "soc", "cyber"], "Cyber Security"),
            (["network"], "Network Engineering"),
            (["linux administrator"], "Linux Administration"),
            (["windows administrator"], "Windows Administration"),
            (["system administrator"], "System Administration"),

            # Mobile / Platforms
            (["android"], "Android Development"),
            (["ios", "swift"], "iOS Development"),
            (["flutter", "mobile app"], "Cross-platform Mobile Development"),
            (["salesforce"], "Salesforce"),
            (["servicenow"], "ServiceNow"),
            (["rpa", "uipath"], "RPA/Automation"),
            (["technical writer", "documentation"], "Technical Documentation"),
        ]

        for keywords, cluster in mapping_rules:
            if any(keyword in text for keyword in keywords):
                return cluster

        return "General IT"
    
    def _build_target_salary_note(
        self,
        target_role: str,
        target_cluster: str,
        fit_level: str,
        experience_label: str,
    ) -> str:
        normalized_fit = fit_level.lower()

        if "high" in normalized_fit:
            fit_note = (
                "This looks like a realistic adjacent move based on your current profile."
            )
        elif "low" in normalized_fit:
            fit_note = (
                "This is a stretch path and may require stronger preparation before targeting the upper end of this range."
            )
        else:
            fit_note = (
                "This is a possible transition path, but you should close key skill gaps before expecting stronger offers."
            )

        return (
            f"{target_role} is mapped to the {target_cluster} salary band using your "
            f"{experience_label} experience level. {fit_note}"
        )

    def _load_salary_band(
        self,
        role_cluster: str,
        role_intelligence: Optional[RoleIntelligenceResult]
    ) -> Optional[Dict[str, Any]]:

        primary_cluster = role_cluster

        if role_intelligence and role_intelligence.primary_cluster:
            primary_cluster = role_intelligence.primary_cluster

        return self._load_salary_band_by_cluster(primary_cluster)

    def _load_salary_band_by_cluster(
        self,
        cluster: str
    ) -> Optional[Dict[str, Any]]:
        """
        Loads salary band from salary_bands_v2 for a given role cluster.

        Example:
        - Application Support
        - Cloud Support
        - DevOps
        - Frontend Engineering
        - API Testing
        """

        if not self.database_url:
            return None

        try:
            connection = psycopg2.connect(self.database_url)
            cursor = connection.cursor(cursor_factory=RealDictCursor)

            cursor.execute(
                """
                select *
                from salary_bands_v2
                where lower(role_key) = lower(%s)
                   or lower(primary_cluster) = lower(%s)
                order by
                  case
                    when lower(role_key) = lower(%s) then 1
                    when lower(primary_cluster) = lower(%s) then 2
                    else 3
                  end
                limit 1
                """,
                (
                    cluster,
                    cluster,
                    cluster,
                    cluster
                )
            )

            row = cursor.fetchone()

            cursor.close()
            connection.close()

            if row:
                return dict(row)

            return None

        except Exception as e:
            print(f"Failed to load salary band v2 for {cluster}: {e}")
            return None
        
    def _select_experience_band(
        self,
        experience_years: float,
        salary_band: Dict[str, Any]
    ) -> Tuple[float, float, str]:

        if experience_years < 2:
            return (
                float(salary_band["entry_min_lpa"]),
                float(salary_band["entry_max_lpa"]),
                "Entry"
            )

        if experience_years < 5:
            return (
                float(salary_band["early_min_lpa"]),
                float(salary_band["early_max_lpa"]),
                "Early/Mid"
            )

        if experience_years < 8:
            return (
                float(salary_band["mid_min_lpa"]),
                float(salary_band["mid_max_lpa"]),
                "Mid/Senior"
            )

        if experience_years < 12:
            return (
                float(salary_band["senior_min_lpa"]),
                float(salary_band["senior_max_lpa"]),
                "Senior/Lead"
            )

        return (
            float(salary_band["lead_min_lpa"]),
            float(salary_band["lead_max_lpa"]),
            "Lead+"
        )

    def _city_multiplier(self, city: str) -> float:
        normalized_city = city.strip().lower()

        city_multipliers = {
            "bangalore": 1.10,
            "bengaluru": 1.10,
            "gurgaon": 1.10,
            "gurugram": 1.10,
            "hyderabad": 1.08,
            "mumbai": 1.08,
            "pune": 1.05,
            "noida": 1.00,
            "delhi": 1.00,
            "new delhi": 1.00,
            "chennai": 1.00,
            "kolkata": 0.92,
            "ahmedabad": 0.92,
            "jaipur": 0.90,
            "indore": 0.88,
            "chandigarh": 0.92,
            "kochi": 0.88,
            "coimbatore": 0.86,
        }

        return city_multipliers.get(normalized_city, 0.95)

    def _skill_readiness_multiplier(
        self,
        role_intelligence: Optional[RoleIntelligenceResult]
    ) -> float:

        if not role_intelligence:
            return 1.0

        matched_count = len(role_intelligence.matched_skills or [])
        missing_core_count = len(role_intelligence.missing_core_skills or [])
        missing_growth_count = len(role_intelligence.missing_growth_skills or [])
        high_priority_missing_count = len(
            role_intelligence.high_priority_missing_skills or []
        )

        total_signal_count = (
            matched_count +
            missing_core_count +
            missing_growth_count
        )

        if total_signal_count == 0:
            return 1.0

        readiness_ratio = matched_count / total_signal_count

        if readiness_ratio >= 0.75 and high_priority_missing_count <= 2:
            return 1.08

        if readiness_ratio >= 0.55:
            return 1.0

        if readiness_ratio >= 0.35:
            return 0.95

        return 0.90

    def _calculate_salary_gap(
        self,
        current_salary: float,
        market_min: float,
        market_max: float
    ) -> str:

        if current_salary < market_min:
            min_gap = round(market_min - current_salary, 1)
            max_gap = round(market_max - current_salary, 1)
            return f"+{min_gap}L to +{max_gap}L"

        if current_salary > market_max:
            return "You are above the estimated market range"

        return "You are within the expected market range"

    def _build_confidence_note(
        self,
        salary_band: Dict[str, Any],
        role_intelligence: Optional[RoleIntelligenceResult],
        experience_label: str,
        city: str,
        skill_multiplier: float
    ) -> str:

        role_confidence = "unknown"

        if role_intelligence:
            role_confidence = role_intelligence.confidence

        skill_note = "balanced skill readiness"

        if skill_multiplier > 1.0:
            skill_note = "strong skill readiness"
        elif skill_multiplier < 1.0:
            skill_note = "some important skills still missing"

        return (
            f"Medium - Phase 2 salary estimate based on role cluster, "
            f"experience band ({experience_label}), city factor ({city}), "
            f"role mapping confidence ({role_confidence}), and {skill_note}. "
            f"This is still an estimate, not verified live market data."
        )

    def _fallback_salary(
        self,
        profile: CareerProfileRequest,
        role_cluster: str
    ) -> SalaryInsight:

        salary_bands = {
            "Backend Engineering": [
                (0, 2, 4, 8),
                (2, 5, 8, 18),
                (5, 8, 16, 32),
                (8, 15, 28, 55)
            ],
            "Frontend Engineering": [
                (0, 2, 3.5, 7),
                (2, 5, 7, 16),
                (5, 8, 14, 28),
                (8, 15, 24, 48)
            ],
            "Testing/QA": [
                (0, 2, 2.5, 5),
                (2, 5, 4, 9),
                (5, 8, 7, 14),
                (8, 15, 12, 22)
            ],
            "Application Support": [
                (0, 2, 2.5, 5),
                (2, 5, 5, 10),
                (5, 8, 8, 16),
                (8, 15, 14, 26)
            ],
            "Business Analysis": [
                (0, 2, 3.5, 7),
                (2, 5, 6, 14),
                (5, 8, 11, 25),
                (8, 15, 20, 42)
            ],
            "General IT": [
                (0, 2, 3, 6),
                (2, 5, 5, 12),
                (5, 8, 9, 22),
                (8, 15, 16, 35)
            ]
        }

        bands = salary_bands.get(role_cluster, salary_bands["General IT"])

        selected_band = bands[-1]

        for band in bands:
            min_exp, max_exp, min_lpa, max_lpa = band
            if min_exp <= profile.experience_years < max_exp:
                selected_band = band
                break

        _, _, min_lpa, max_lpa = selected_band

        city_multiplier = self._city_multiplier(profile.city)

        market_min = round(min_lpa * city_multiplier, 1)
        market_max = round(max_lpa * city_multiplier, 1)

        salary_gap = self._calculate_salary_gap(
            profile.current_salary_lpa,
            market_min,
            market_max
        )

        return SalaryInsight(
            current_salary_lpa=profile.current_salary_lpa,
            market_min_lpa=market_min,
            market_max_lpa=market_max,
            salary_gap_lpa=salary_gap,
            confidence="Low/Medium - fallback salary estimate because Salary Engine v2 band was not found."
        )
    
    def _normalize_text(self, text: str) -> str:
        text = text.lower().strip()
        text = text.replace("/", " ")
        text = text.replace("-", " ")
        text = text.replace("_", " ")
        text = text.replace("&", " and ")
        text = re.sub(r"[^a-z0-9+#. ]", " ", text)
        text = re.sub(r"\s+", " ", text)
        return text.strip()